# -*- coding: utf-8 -*-
"""northwind.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zYqspTo5dRAY8fW5oJp40D2zpFPlHEvp
"""

import sqlite3
conn = sqlite3.connect('northwind_small.sqlite3')
curs = conn.cursor()

query = """SELECT name FROM sqlite_master WHERE type='table' ORDER BY
name;"""
curs.execute(query).fetchall()

query = """SELECT ProductName FROM Product
ORDER BY UnitPrice DESC 
LIMIT 10;"""
print('10 more expensive items by unitprice:', curs.execute(query).fetchall())

query = """SELECT SUM(HireDate - BirthDate) 
/ COUNT(*) FROM Employee;"""
print('Average age at hire:', curs.execute(query).fetchall()[0][0], 'years old')

query = """
SELECT ProductName, CompanyName
FROM Product
INNER JOIN Supplier
ON Product.SupplierId = Supplier.id
GROUP BY ProductName
ORDER BY UnitPrice DESC 
LIMIT 10;"""
print('The ten more expsenives items and their supplilers:',
      curs.execute(query).fetchall())

query = """
SELECT CategoryName
FROM Product
INNER JOIN Category
ON Product.CategoryId = Category.id
GROUP BY CategoryName
ORDER BY count(*) DESC
LIMIT 1;"""
print('Largest category by unique products:',curs.execute(query).fetchall()[0][0])











